# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Product', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Order', models.CharField(max_length=200)),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
